!FOLLOWING IS THE DOWNHILL SIMPLEX METHOD
!ALGO:
!1. START WITH THE SIMPLEX =DIM+1, AND FIND ITS CENTROID
!2. TAKE THE REFLECTION(R) OF THE WORST POINT(S(3,:)) AND CHECK THE FUNCTION VALUE
!	I. IF THE F(R) IS IN-BETWEEN MIN AND MAX RANGE THEN ASSIGN THE REFLECTED POIN AS NEW WORST POINT
!	II. IF F(R) IS EVEN LESS THAN BEST POINT THEN EXPAND (E) IN  THAT DIRECTION FURTHER
!		A. IF E IS BETTER THAN R THEN ASSIGN THE E AS THE BEST POINT (S(1,:))
!		B. IF R IS BETTER THAN E THEN ASSIGN THE R AS THE BEST POINT (S(1,:))
!	III. UF THE F(R) IS GREATER THAN THE F(S(3,:)) THEN
!		A. IF F(R)>F(S(2,:)) THEN CHECK FOR THE CONTRACTION(C).   
!				IF F(C) IS LESS THAN F(R) THEN ASSIGN C AS THE WORST POINT
!				IF F(C) GREATER THAN F(R) THEN SHRINK THE SIMPLEX TOWARDS THE BEST POINT			

!CONTAINED SUBROUTINES/FUNCTION ARE: 
!SUB:DOWN_HILL, SORT_PTS,CENTROID; FUNC: F

PROGRAM SIMPLEX
REAL (SELECTED_REAL_KIND(15,307))  	:: S(3,2),FTOL

PRINT *, 'ENTER THE POINTS'
PRINT *, 'ENTER THE POINT 1'
READ *, S(1,1),S(1,2)
PRINT *, 'ENTER THE POINT 2'
READ *, S(2,1),S(2,2)
PRINT *, 'ENTER THE POINTS 3'
READ *, S(3,1),S(3,2)

!FTOL=EPSILON(1.)
FTOL=1.E-10

CALL DOWN_HILL(S,FTOL)

!*******************************************************************************
CONTAINS
!***********************************

FUNCTION F(P)
IMPLICIT NONE
REAL (SELECTED_REAL_KIND(15,307)) :: X,Y,F,P(2)

X=P(1)
Y=P(2)
F=100*(Y-X**2)**2 + (1-X)**2
END FUNCTION F
!***************************************

SUBROUTINE DOWN_HILL(S,FTOL)
REAL (SELECTED_REAL_KIND(15,307)), INTENT(INOUT):: S(3,2), FTOL
REAL (SELECTED_REAL_KIND(15,307)), DIMENSION(2)	:: M, M_OLD=(/0,0/), M_NEW, R, E, C
REAL (SELECTED_REAL_KIND(15,307))				:: RTOL, TIN=10.E-10, ALPHA=1., GAMMA=2., RHO=.5, SIGMA=.5
INTEGER 										:: I
LOGICAL 										:: B

OPEN(10, FILE="DOWN-HILL-SIMPLEX new-2.DAT")
  DO I=1,1000
  WRITE (10,*)((S(J,K),K=1,2),J=1,3)

  CALL SORT_PTS(S)															!STEP 1: SORT THE POINTS
  !RTOL=2.0*ABS(F(S(3,:))- F(S(1,:)))/(ABS(F(S(3,:)))+ ABS(F(S(1,:)))+ TIN )	!CALCULATE THE TOLRENCE (FROM THE PRESS BOOK)
  CALL CENTROID(M,S)					!2 CALCULATE THE CENTROID
  PRINT *, 'CENTROID',M
  M_NEW=M
  RTOL= ABS(F(M_OLD)-F(M_NEW))
 
 IF (RTOL<FTOL)THEN
  	PRINT *,'OBTAINED MIN POINT IS=', S(1,:)
  	WRITE (10,*)((S(J,K),K=1,2),J=1,3)
  	RETURN
  END IF
  M_OLD= M_NEW

  R= M + ALPHA*(M-S(3,:))			!3 REFLECTION OF THE WORST POINT P3 OVER M	! RETURNS REFLECTED COORDINATE 'R'
  IF ( F(S(1,:))<F(R).AND. F(R)<F(S(3,:)) )THEN
	S(3,:)=R
  ELSEIF (F(R)<F(S(1,:)))THEN
	E= R + GAMMA*(R-M)				! RETURNS EXPANDED COORDINATE 'E'
   	IF(F(E)<F(R)) THEN
      S(3,:)=E
      ELSE 
       S(3,:)=R
    END IF
  ELSE
    B=.TRUE.
   	IF (F(R)>=F(S(2,:))) THEN
   	  C= RHO*R + (1-RHO)*M		!RETRURNS CONTRACTED POINT C
      IF (F(C)<F(R))THEN
        S(3,:)=C
        B=.FALSE.
      END IF
    END IF
      
    IF(B) THEN
      S(2,:)=S(1,:)+SIGMA*(S(2,:)-S(1,:))		! SHRINK TOWARDS THE BEST SOLUTION CANDIDATE 
      S(3,:)=S(1,:)+SIGMA*(S(3,:)-S(1,:))
    END IF
  END IF 
  PRINT *, 'ITERATION NO=', I
  !PRINT *, 'NEW SIMPLEX=',((S(J,K),K=1,2),J=1,3)      
  PRINT*, 'The answer is: '
  PRINT "(F6.3 )", ((S(J,K),K=1,2),J=1,3)
END DO
PRINT *,'OBTAINED MIN POINT IS=', S(1,:)
END SUBROUTINE DOWN_HILL
!**********************************

SUBROUTINE SORT_PTS(S)
REAL (SELECTED_REAL_KIND(15,307))					:: TEMP(2)
REAL (SELECTED_REAL_KIND(15,307)), INTENT(INOUT)	:: S(3,2)
INTEGER 			:: I,J,N=3
DO I=1,N-1
  DO J=1,N-1
    IF (F(S(J,:))>F(S(J+1,:)))THEN
      TEMP=S(J,:)
      S(J,:)=S(J+1,:)
      S(J+1,:)=TEMP 
	END IF
  END DO
END DO
END SUBROUTINE SORT_PTS
!***********************************

SUBROUTINE CENTROID(C,S)
REAL (SELECTED_REAL_KIND(15,307)), INTENT(OUT)	:: C(2)
REAL (SELECTED_REAL_KIND(15,307)), INTENT(IN)	:: S(3,2)
C(1)=SUM(S(:,1))/3
C(2)=SUM(S(:,2))/3
END SUBROUTINE CENTROID
!***********************************

END PROGRAM SIMPLEX