function [segy_tr_header]=segy_trace_header()

segy_tr_header.tr_seq_line=0;                    % 1      imp
segy_tr_header.tr_seq_segy=0;                    % 5       
segy_tr_header.fld_rec_no =0;                    % 9      imp
segy_tr_header.fld_rec_tr_no =0;                 % 13     imp
segy_tr_header.src =0;                           % 17
segy_tr_header.ensemble_no =0;                   % 21 
segy_tr_header.ensemble_tr_no=0;                 % 25
segy_tr_header.tr_id =0;                         % 29     imp
segy_tr_header.vert_sum =0;                      % 31
segy_tr_header.hor_sum =0;                       % 33
segy_tr_header.use =0;                           % 35
segy_tr_header.src_rec_dis =0;                   % 37
segy_tr_header.elev_rec =0;                      % 41
segy_tr_header.elev_src =0;                      % 45    
segy_tr_header.depth_src =0;                     % 49
segy_tr_header.datum_rec=0;                      % 53
segy_tr_header.datum_src =0;                     % 57
segy_tr_header.depth_src =0;                     % 61
segy_tr_header.depth_gr =0;                      % 65
segy_tr_header.scaler1 =0;                       % 69
segy_tr_header.scaler2 =0;                       % 71
segy_tr_header.src_x =0;                         % 73
segy_tr_header.src_y =0;                         % 77
segy_tr_header.gr_x =0;                          % 81
segy_tr_header.gr_y =0;                          % 85
segy_tr_header.xy_unit =0;                       % 89 
segy_tr_header.vel_weather =0;                   % 91 
segy_tr_header.vel_subweather =0;                % 93
segy_tr_header.uphole_t_src =0;                  % 95
segy_tr_header.uphole_t_gr =0;                   % 97
segy_tr_header.static_src =0;                    % 99
segy_tr_header.static_gr =0;                     % 101
segy_tr_header.static_total =0;                  % 103
segy_tr_header.time_lagA =0;                     % 105
segy_tr_header.time_lagB =0;                     % 107
segy_tr_header.time_delay =0;                    % 109
segy_tr_header.time_mute0 =0;                    % 111
segy_tr_header.time_mute1 =0;                    % 113
segy_tr_header.ns =0;                            % 115    imp
segy_tr_header.dt =0;                            % 117    imp
segy_tr_header.gain_type =0;                     % 119
segy_tr_header.gain_const_instrument =0;         % 121
segy_tr_header.gain_const_instrument_initial =0; % 123
segy_tr_header.correlated =0;                    % 125
segy_tr_header.sweep_freq0 =0;                   % 127
segy_tr_header.sweep_freq1 =0;                   % 129
segy_tr_header.sweep_length =0;                  % 131
segy_tr_header.sweep_type =0;                    % 133
segy_tr_header.sweep_taper0 =0;                  % 135
segy_tr_header.sweep_taper1 =0;                  % 137
segy_tr_header.taper_type =0;                    % 139
segy_tr_header.filter_alias_freq =0;             % 141
segy_tr_header.filter_alias_slope =0;            % 143
segy_tr_header.filter_notch_freq =0;             % 145
segy_tr_header.filter_notch_slope =0;            % 147
segy_tr_header.filter_low_cut_freq =0;           % 149
segy_tr_header.filter_high_cut_freq =0;          % 151
segy_tr_header.slope_low_cut =0;                 % 153
segy_tr_header.slope_high_cut =0;                % 155
segy_tr_header.time_year =0;                     % 157
segy_tr_header.time_day =0;                      % 159
segy_tr_header.time_hr =0;                       % 161
segy_tr_header.time_min =0;                      % 163
segy_tr_header.tiem_sec =0;                      % 165
segy_tr_header.time_basis =0;                    % 167
segy_tr_header.tr_wt_factor =0;                  % 169
segy_tr_header.gp_gr_no_roll =0;                 % 171
segy_tr_header.gp_gr_no_segy_tr0 =0;             % 173
segy_tr_header.gp_gr_no_trace1 =0;               % 175
segy_tr_header.gap_size =0;                      % 177
segy_tr_header.taper_dist =0;                    % 179
segy_tr_header.cdp_x =0;                         % 181
segy_tr_header.cdp_y =0;                         % 185
segy_tr_header.inline =0;                        % 189
segy_tr_header.xline =0;                         % 193
segy_tr_header.src_no =0;                        % 197
segy_tr_header.scale1 =0;                        % 201
segy_tr_header.tr_unit =0;                       % 203
segy_tr_header.transdunction_const =0;           % 205   
segy_tr_header.transdunction_unit =0;            % 211   
segy_tr_header.device_id =0;                     % 213
segy_tr_header.scaler2 =0;                       % 215
segy_tr_header.src_type =0;                      % 217
segy_tr_header.src_energy_dir_mentissa =0;                % 219 
segy_tr_header.src_energy_dir_exponent =0;                % 223 
segy_tr_header.src_measurement_mentissa =0;               % 225
segy_tr_header.src_measurement_exponent =0;               % 229
segy_tr_header.src_measurement_unit =0;          % 231 
segy_tr_header.unassigned=zeros(2,1);            % 233-240    8-Bytes