!PROGRAM FOR THE SIMULATED ANNEALING

PROGRAM SA
IMPLICIT NONE
REAL		::	T,C,PROB,R
REAL		:: PNEW(2),PCURR(2),PBEST(2), FNEW,FCURR,FBEST, dF
INTEGER 	:: I,N,K
PARAMETER (N=200, C=.98)
!T = INI_TEMP()
T=100
PRINT*,'INTITIAL TEMP', T
PNEW=NEW_POINT()		!NEW POINT
PCURR=PNEW			!CURRENT POINT

PBEST=PNEW			!BEST POINT
FBEST=F(PBEST(1),PBEST(2))
PRINT*, 'BEST POINT= ',PBEST, '; F=',FBEST
CALL RANDOM_SEED()

K=0    
DO WHILE(T>.001)
  PRINT *, "FLAG ", T,K		!*****FLAG
  DO I=1,N
    FCURR=F(PCURR(1),PCURR(2))
    PRINT*,'CURRENT',PCURR, FCURR			!,'CURR',PCURR,'BEST',PBEST
  	PNEW=NEW_POINT()			!V_POINT(PNEW(1),PNEW(2))
  	FNEW=F(PNEW(1),PNEW(2))

    dF=FNEW-FCURR
  	IF (dF<=0) THEN
      PCURR=PNEW
      FCURR=FNEW
      IF (FCURR<FBEST) THEN 
        PBEST=FCURR
      	FBEST=FCURR
      END IF
  	ELSE						! WHEN dF>0
      PROB=exp(-dF/T)			!PROBABILITY 
      R= RANDOM_GAUSS()
      PRINT*, 'RAND= ',R
      IF (PROB>R) THEN
   	    PCURR=PNEW
      	FCURR=FNEW
      END IF
  	END IF
    PRINT*,'BEST',PBEST,FBEST			!,'CURR',PCURR,'BEST',PBEST
  END DO
  K=K+1   
  T=T*(C**K)
END DO

PRINT *,'BEST POINT IS -',PBEST

!****************************************************
CONTAINS
!****************************************************
FUNCTION F(X,Y)			!FUNCTION DEFINED HERE
IMPLICIT NONE
REAL	:: X,Y,F,PI
!F=X**2 + Y**2
F=100*((Y-X**2)**2) + ((1-X)**2)
!PI=4*ATAN(1.)
!F=10+(X**2-10*COS(2*PI*X)) + (Y**2 + 10*COS(2*PI*Y))

END FUNCTION F
!------------------------------------------------
FUNCTION NEW_POINT()		!CREATES A NEW POINT
	IMPLICIT NONE
	REAL 	::  a,b,c,d,R, NEW_POINT(2)
	a=-5; b=5; c=-5; d=5
	CALL RANDOM_SEED()
	CALL RANDOM_NUMBER(R)
	NEW_POINT(1)=a+ R*(b-a)
	CALL RANDOM_NUMBER(R)
	NEW_POINT(2)=c+ R*(d-c)
	PRINT*, 'NEW POINT= ',NEW_POINT
	END FUNCTION NEW_POINT
!-----------------------------------------------
!FUNCTION V_POINT(X,Y)	!VICINITY POINT
!IMPLICIT NONE
!REAL :: X,Y,V_POINT
!END FUNCTION V_POINT
!-----------------------------------------------

FUNCTION INI_TEMP()		!FINDS THE INITIAL TEMP
	IMPLICIT NONE
	REAL	:: VAR(2),T0, T1,INI_TEMP
	INTEGER :: I

	VAR=NEW_POINT()
	T0 = F(VAR(1),VAR(2))
	DO I=1,50
  		VAR=NEW_POINT()
  		T1 = F(VAR(1),VAR(2))
  		IF(T1>T0) THEN 
    		T0=T1
 		END IF
	END DO
	INI_TEMP=T0
	END FUNCTION INI_TEMP
!-----------------------------------------------
FUNCTION RANDOM_GAUSS()
	IMPLICIT NONE	
	REAL	:: NO1,NO2,PI,STD_DEV,MEAN,RANDOM_GAUSS
	
	MEAN = 0
	STD_DEV= 1
	PI=4.0D0*ATAN(1.0D0)
	
	CALL RANDOM_NUMBER(NO1)
	CALL RANDOM_NUMBER(NO2)
	
	RANDOM_GAUSS=STD_DEV*SQRT(-2*LOG(NO1))*COS(2*PI*NO2)+MEAN

	END FUNCTION RANDOM_GAUSS

END PROGRAM SA