function [segy_textual_file_header]= textual_file_header()

%12345678901234567890123456789012345678901234567890123456789012345678901234567890
segy_textual_file = [...
'C 1 CLIENT                        COMPANY                       CREW NO         ';         
'C 2 LINE            AREA                        MAP ID                          '; ...                          
'C 3 REEL NO           DAY-START OF REEL     YEAR      OBSERVER                  '; ...                   
'C 4 INSTRUMENT: MFG            MODEL            SERIAL NO                       '; ...                       
'C 5 DATA TRACES/RECORD        AUXILIARY TRACES/RECORD         CDP FOLD          '; ...           
'C 6 SAMPLE INTERNAL         SAMPLES/TRACE       BITS/IN      BYTES/SAMPLE       '; ...        
'C 7 RECORDING FORMAT        FORMAT THIS REEL        MEASUREMENT SYSTEM          '; ...           
'C 8 SAMPLE CODE: FLOATING PT     FIXED PT     FIXED PT-GAIN     CORRELATED      '; ...      
'C 9 GAIN  TYPE: FIXED     BINARY     FLOATING POINT     OTHER                   '; ...                   
'C10 FILTERS: ALIAS     HZ  NOTCH     HZ  BAND    -     HZ  SLOPE    -    DB/OCT '; ...  
'C11 SOURCE: TYPE            NUMBER/POINT        POINT INTERVAL                  '; ...                   
'C12     PATTERN:                           LENGTH        WIDTH                  '; ...                   
'C13 SWEEP: START     HZ  END     HZ  LENGTH      MS  CHANNEL NO     TYPE        '; ...         
'C14 TAPER: START LENGTH       MS  END LENGTH       MS  TYPE                     '; ...                      
'C15 SPREAD: OFFSET        MAX DISTANCE        GROUP INTERVAL                    '; ...                    
'C16 GEOPHONES: PER GROUP     SPACING     FREQUENCY     MFG          MODEL       '; ...        
'C17     PATTERN:                           LENGTH        WIDTH                  '; ...                   
'C18 TRACES SORTED BY: RECORD     CDP     OTHER                                  '; ...                                  
'C19 AMPLITUDE RECOVEY: NONE      SPHERICAL DIV       AGC    OTHER               '; ...                
'C20 MAP PROJECTION                      ZONE ID       COORDINATE UNITS          '; ...           
'C21 PROCESSING:                                                                 '; ...                                                                  
'C22 PROCESSING:                                                                 '; ...                                                                  
'C23                                                                             ' ; ...                                                                             
'C24                                                                             '; ...                                                                             
'C25                                                                             '; ...                                                                             
'C26                                                                             '; ...                                                                             
'C27                                                                             '; ...                                                                             
'C28                                                                             '; ...                                                                             
'C29                                                                             '; ...                                                                             
'C30                                                                             '; ...                                                                             
'C31                                                                             '; ...                                                                             
'C32                                                                             '; ...                                                                             
'C33                                                                             '; ...                                                                             
'C34                                                                             '; ...                                                                             
'C35                                                                             '; ...                                                                             
'C36                                                                             '; ...                                                                             
'C37                                                                             '; ...                                                                             
'C38                                                                             '; ...                                                                             
'C39                                                                             '; ...                                                                             
'C40 END EBCDIC                                                                  ';];
%12345678901234567890123456789012345678901234567890123456789012345678901234567890

for i=1:40
   p=(i-1)*80 +1 ;
   q= i*80;
   segy_textual_file_header(p:q)=segy_textual_file(i,:);
end
%segy_textual_file_header = [...
% 'C 1 CLIENT                        COMPANY                       CREW NO', ...         
% 'C 2 LINE            AREA                        MAP ID ', ...                          
% 'C 3 REEL NO           DAY-START OF REEL     YEAR      OBSERVER', ...                   
% 'C 4 INSTRUMENT: MFG            MODEL            SERIAL NO', ...                       
% 'C 5 DATA TRACES/RECORD        AUXILIARY TRACES/RECORD         CDP FOLD', ...           
% 'C 6 SAMPLE INTERNAL         SAMPLES/TRACE       BITS/IN      BYTES/SAMPLE', ...        
% 'C 7 RECORDING FORMAT        FORMAT THIS REEL        MEASUREMENT SYSTEM', ...           
% 'C 8 SAMPLE CODE: FLOATING PT     FIXED PT     FIXED PT-GAIN     CORRELATED ', ...      
% 'C 9 GAIN  TYPE: FIXED     BINARY     FLOATING POINT     OTHER ', ...                   
% 'C10 FILTERS: ALIAS     HZ  NOTCH     HZ  BAND    -     HZ  SLOPE    -    DB/OCT ', ...  
% 'C11 SOURCE: TYPE            NUMBER/POINT        POINT INTERVAL', ...                   
% 'C12     PATTERN:                           LENGTH        WIDTH', ...                   
% 'C13 SWEEP: START     HZ  END     HZ  LENGTH      MS  CHANNEL NO     TYPE', ...         
% 'C14 TAPER: START LENGTH       MS  END LENGTH       MS  TYPE', ...                      
% 'C15 SPREAD: OFFSET        MAX DISTANCE        GROUP INTERVAL', ...                    
% 'C16 GEOPHONES: PER GROUP     SPACING     FREQUENCY     MFG          MODEL', ...        
% 'C17     PATTERN:                           LENGTH        WIDTH', ...                   
% 'C18 TRACES SORTED BY: RECORD     CDP     OTHER', ...                                  
% 'C19 AMPLITUDE RECOVEY: NONE      SPHERICAL DIV       AGC    OTHER', ...                
% 'C20 MAP PROJECTION                      ZONE ID       COORDINATE UNITS', ...           
% 'C21 PROCESSING:', ...                                                                  
% 'C22 PROCESSING:', ...                                                                  
% 'C23 ', ...                                                                             
% 'C24 ', ...                                                                             
% 'C25 ', ...                                                                             
% 'C26 ', ...                                                                             
% 'C27 ', ...                                                                             
% 'C28 ', ...                                                                             
% 'C29 ', ...                                                                             
% 'C30 ', ...                                                                             
% 'C31 ', ...                                                                             
% 'C32 ', ...                                                                             
% 'C33 ', ...                                                                             
% 'C34 ', ...                                                                             
% 'C35 ', ...                                                                             
% 'C36 ', ...                                                                             
% 'C37 ', ...                                                                             
% 'C38 ', ...                                                                             
% 'C39 ', ...                                                                             
% 'C40 END EBCDIC'];
